### ISSUE TITLE
Make ASCII.POWERS_OF_TEN public

### ISSUE THREAD

**Issue by jheusser** [paritytrading/foundation#1]
Might be a tiny suggestion, but if you use `foundation` to write custom ASCII functions which aren't currently implemented you will most likely reimplement the `POWERS_OF_TEN` array, could be handy to have it available as `ASCII.POWERS_OF_TEN`.

**Comment by jvirtanen** [comment]
Yes, make sense. Perhaps a more logical name for it would then be `Longs.POWERS_OF_TEN` as well, what do you think?

**Comment by jvirtanen** [comment]
This is now on `master`, and a release will be cut later this week.
